export const SET_PHIM  = "SET_PHIM";
export const SET_CURRENT_MOVIE = "SET_CURRENT_MOVIE";
export const SET_COMMINGSOON_MOVIE = "SET_COMMINGSOON_MOVIE";
export const SET_FILM_DETAIL = "SET_FILM_DETAIL";
export const SET_THONG_TIN_PHIM = "SET_THONG_TIN_PHIM";
export const SET_AUTO_COMPLETE_FILM = "SET_AUTO_COMPLETE_FILM";

