export const LOGIN = "LOGIN";
export const SAVE_THONG_TIN_TAI_KHOAN = "SAVE_THONG_TIN_TAI_KHOAN";
export const SET_DANH_SACH_NGUOI_DUNG = "SET_DANH_SACH_NGUOI_DUNG";
export const SET_LOAI_NGUOI_DUNG = "SET_LOAI_NGUOI_DUNG";